/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const City = IDL.Record({ 'name' : IDL.Text });
export const Area = IDL.Record({ 'city' : City, 'name' : IDL.Text });
export const Cafe = IDL.Record({
  'id' : IDL.Nat,
  'area' : Area,
  'city' : City,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
});

export const idlService = IDL.Service({
  'addCafe' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        City,
        Area,
        IDL.Text,
        IDL.Tuple(IDL.Float64, IDL.Float64),
      ],
      [],
      [],
    ),
  'getCafeById' : IDL.Func([IDL.Nat], [Cafe], ['query']),
  'listCafes' : IDL.Func([], [IDL.Vec(Cafe)], ['query']),
  'searchCafes' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Cafe)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const City = IDL.Record({ 'name' : IDL.Text });
  const Area = IDL.Record({ 'city' : City, 'name' : IDL.Text });
  const Cafe = IDL.Record({
    'id' : IDL.Nat,
    'area' : Area,
    'city' : City,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  
  return IDL.Service({
    'addCafe' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          City,
          Area,
          IDL.Text,
          IDL.Tuple(IDL.Float64, IDL.Float64),
        ],
        [],
        [],
      ),
    'getCafeById' : IDL.Func([IDL.Nat], [Cafe], ['query']),
    'listCafes' : IDL.Func([], [IDL.Vec(Cafe)], ['query']),
    'searchCafes' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Cafe)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };